// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfOUko5GXvAWH7RXRrvU-5wauIwtZjiis',
    appId: '1:178226635083:web:49f89824ba276e9e7648ce',
    messagingSenderId: '178226635083',
    projectId: 'logingraduationproject',
    authDomain: 'logingraduationproject.firebaseapp.com',
    storageBucket: 'logingraduationproject.firebasestorage.app',
    measurementId: 'G-ET4YZ4JMPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7CpJ94b3UVI_3Qv6YnGCtQFabuidtQhk',
    appId: '1:178226635083:android:395be76dbb0515567648ce',
    messagingSenderId: '178226635083',
    projectId: 'logingraduationproject',
    storageBucket: 'logingraduationproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC14Gw7q9YuV5_RnGAlUBpw3bF7h2HeTM',
    appId: '1:178226635083:ios:bf8d312a869ec68b7648ce',
    messagingSenderId: '178226635083',
    projectId: 'logingraduationproject',
    storageBucket: 'logingraduationproject.firebasestorage.app',
    iosBundleId: 'com.example.graceCycle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfOUko5GXvAWH7RXRrvU-5wauIwtZjiis',
    appId: '1:178226635083:web:80b838ca87d34c077648ce',
    messagingSenderId: '178226635083',
    projectId: 'logingraduationproject',
    authDomain: 'logingraduationproject.firebaseapp.com',
    storageBucket: 'logingraduationproject.firebasestorage.app',
    measurementId: 'G-YF2RSS0XER',
  );
}
